apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "kiali.name" . }}
    chart: {{ template "kiali.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  installation_tag: My Kiali
  deployment:
    view_only_mode: true
  external_services:
  {{ if .Values.grafanaAddr }}
    grafana:
      url: {{ .Values.grafanaAddr }}
  {{ end }}
  {{ if .Values.jaegerAddr }}
    jaeger:
      url: {{ .Values.jaegerAddr }}
  {{ end }}
  {{ if .Values.prometheusAddr }}
    prometheus:
      url: {{ .Values.prometheusAddr }}
  {{ end }}
  server:
    web_root: /mykiali
